{
  "openapi": "3.0.3",
  "info": {
    "title": "API Aplikai Pelaporan Insiden",
    "description": "OpenAPI for Aplikasi Pelaporan Insiden RESTful API",
    "contact": {
      "name": "Jerico Katong",
      "email": "jericokatong@gmail.com"
    },
    "version": "1.0"
  },
  "servers": [{ "url": "http://localhost:5000" }],
  "paths": {
    "/auth/user/register": {
      "post": {
        "tags": ["Authentikasi User"],
        "summary": "Register user",
        "description": "Register user dengan role user biasa",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "konfirmasi_password": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string"
                  }
                },
                "required": ["name", "username", "password"]
              },
              "example": {
                "name": "Hendra Luntungan",
                "username": "hendra1",
                "password": "123456",
                "konfirmasi_password": "123456",
                "role": "user"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success Register",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "username": {
                          "type": "string"
                        },
                        "password": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "code": "201",
                  "status": "CREATED",
                  "data": {
                    "name": "Hendra Luntungan",
                    "username": "hendra1",
                    "password": "123456",
                    "role": "user"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Client Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralError"
                },
                "examples": {
                  "password do not match": {
                    "value": {
                      "code": "400",
                      "status": "BAD_REQUEST",
                      "errors": "Password and confirmation password do not match"
                    }
                  },
                  "Empty Field": {
                    "value": {
                      "code": "400",
                      "status": "BAD_REQUEST",
                      "errors": "Name, Username, Password and password confirmation Fields Are Required"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Failed: username alread exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralError"
                },
                "example": {
                  "code": "409",
                  "status": "CONFLICT",
                  "errors": "Username already exists"
                }
              }
            }
          }
        }
      }
    },
    "/auth/user/login": {
      "post": {
        "tags": ["Authentikasi User"],
        "summary": "Login User",
        "description": "Login user untuk admin dan user biasa",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "username": "hendra1",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success Login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id_user": {
                          "type": "string"
                        },
                        "username": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        },
                        "token": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "code": "200",
                  "status": "OK",
                  "data": {
                    "id_user": "21dab398-7fd2-4d4a-80ac-5b3eea6e",
                    "username": "hendra1",
                    "role": "user",
                    "token": "ajfoapfijaofjifjaofjpaiofjaofjaopfjapofjaofjjeriqroiojafoiaj"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Client Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralError"
                },
                "examples": {
                  "User Not Found": {
                    "value": {
                      "code": "400",
                      "status": "BAD_REQUEST",
                      "errors": "User Not Found"
                    }
                  },
                  "Incorrect Password": {
                    "value": {
                      "code": "400",
                      "status": "BAD_REQUEST",
                      "errors": "Incorrect Password"
                    }
                  },
                  "Empty Field": {
                    "value": {
                      "code": "400",
                      "status": "BAD_REQUEST",
                      "errors": "Username and Password Fields Are Required"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/user/logout": {
      "delete": {
        "tags": ["Authentikasi User"],
        "summary": "Logout User",
        "description": "User melakukan Logout",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "type": "string"
                  }
                },
                "example": {
                  "token": "afjaofjiapfjapfjojrqorjqoienviqnvqopijqrpvnqppqrijqporjj"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Succes Logout",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "success": {
                      "type": "boolean"
                    }
                  },
                  "example": {
                    "code": "200",
                    "status": "OK",
                    "success": true
                  }
                }
              }
            }
          },
          "401": {
            "description": "User belum login",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralError"
                },
                "example": {
                  "code": "401",
                  "status": "UNAUTHORIZED",
                  "errors": "User hasn't login yet"
                }
              }
            }
          },
          "404": {
            "description": "User is not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralError"
                },
                "example": {
                  "code": "404",
                  "status": "NOT_FOUND",
                  "errors": "User is not found"
                }
              }
            }
          }
        }
      }
    },
    "/api/user/{id_user}": {
      "get": {
        "tags": ["User"],
        "summary": "Get user by ID",
        "description": "Get detail user by ID",
        "parameters": [
          {
            "name": "id_user",
            "description": "Mendapatkan detail user berdasarkan id user",
            "required": true,
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Success get user by ID",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id_user": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "username": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "example": {
                    "code": "200",
                    "status": "OK",
                    "data": {
                      "id_user": "21dab398-7fd2-4d4a-80ac-5b3eea6e",
                      "name": "hendra luntungan",
                      "username": "hendra1",
                      "role": "user"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralError"
                },
                "example": {
                  "code": "404",
                  "status": "NOT_FOUND",
                  "errors": "User is not found"
                }
              }
            }
          }
        }
      }
    },
    "/api/users": {
      "get": {
        "tags": ["User"],
        "summary": "Get All User",
        "description": "Get All Detail User",
        "responses": {
          "200": {
            "description": "Success Get All User",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id_user": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "username": {
                            "type": "string"
                          },
                          "role": {
                            "type": "string"
                          },
                          "token": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "code": "200",
                  "status": "OK",
                  "data": [
                    {
                      "id_user": "21dab398-7fd2-4d4a-80ac-5b3eea6e",
                      "name": "hendra luntungan",
                      "username": "hendra1",
                      "role": "admin",
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiMjFkYWIzOTgtN2ZkMi00ZDRhLTgwYWMtNWIzZWVhNmUiLCJ1c2VybmFtZSI6ImhlbmRyYTEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTU3Nzc2NDMsImV4cCI6MTY5NTg2NDA0M30.A0rbFDHya8qoNj1BAYraxu-4fT3dP8iVpqXyrrO1Jo0"
                    },
                    {
                      "id_user": "2e4d4319-56c8-4c43-a298-cebb3501",
                      "name": "Ovel Tjia",
                      "username": "ovel1",
                      "role": "user",
                      "token": null
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/jenis_pasien": {
      "get": {
        "tags": ["Jenis Pasien"],
        "summary": "Get All Jenis Pasien",
        "description": "Get All nama jenis pasien untuk kebutuhan input laporan",
        "responses": {
          "200": {
            "description": "Success Get All Jenis Pasien",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id_jenis_pasien": {
                            "type": "integer"
                          },
                          "nama_jenis_pasien": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "code": "200",
                  "status": "OK",
                  "data": [
                    {
                      "id_jenis_pasien": 1,
                      "nama_jenis_pasien": "Pasien rawat inap"
                    },
                    {
                      "id_jenis_pasien": 2,
                      "nama_jenis_pasien": "Pasien rawat jalan"
                    },
                    {
                      "id_jenis_pasien": 3,
                      "nama_jenis_pasien": "Pasien UGD"
                    },
                    {
                      "id_jenis_pasien": 4,
                      "nama_jenis_pasien": "Lain-lain"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Data jenis pasien tidak ditemukan / tidak ada",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralError"
                },
                "example": {
                  "code": "404",
                  "status": "NOT_FOUND",
                  "errors": "No Data Jenis Pasien Found"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Jenis Pasien"],
        "summary": "Post Jenis Pasien",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nama_jenis_pasien": {
                    "type": "string"
                  }
                },
                "example": {
                  "nama_jenis_pasien": "Pasien rawat inap"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success Post Jenis Pasien",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id_jenis_pasien": {
                          "type": "integer"
                        },
                        "nama_jenis_pasien": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "code": "200",
                  "status": "OK",
                  "data": {
                    "id_jenis_pasien": 1,
                    "nama_jenis_pasien": "Pasien rawat inap"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/laporan": {
      "get": {
        "tags": ["Laporan"],
        "responses": {}
      }
    }
  },
  "components": {
    "schemas": {
      "GeneralError": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "errors": {
            "type": "string"
          }
        }
      }
    }
  }
}
